  # Your full node ip, this is where your miners are also mining to
NodeIP: XXX.XXX.XXX.XXX
  # Your full node port, the same as used by your miners
NodePort: 6434
  # Your full node username and password
NodeUser: someusername
NodePass: somepassword

  # Database information for the DB this will store mining data to.
ServiceDBUser: username
ServiceDBPass: password
ServiceDBHost: 127.0.0.1
ServiceDBPort: 3306
ServiceDBName: YourDBNameHere

  # The port THIS service should run on and expose it's rpc to get mining stats
ServicePort: 9143

