  # Your full node ip, this is where your miners are also mining to
NodeIP: XXX.XXX.XXX.XXX
  # Your full node port, the same as used by your miners
NodePort: 6434
  # Your full node username and password
NodeUser: someusername
NodePass: somepassword

  # The port THIS service should run on and expose it's rpc to get mining stats
ServicePort: 9143

